//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSessionOne.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WsrTestEntities : DbContext
    {
        public WsrTestEntities()
            : base("name=WsrTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<StatusRequest> StatusRequest { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeRequest> TypeRequest { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAsp> UserAsp { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
    }
}
