//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSessionOne.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public Nullable<int> IDTypeRequest { get; set; }
        public string Subdivision { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int IDStatusRequest { get; set; }
        public string Reason { get; set; }
        public Nullable<int> IDVisitor { get; set; }
    
        public virtual StatusRequest StatusRequest { get; set; }
        public virtual TypeRequest TypeRequest { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
